services:
  miner:
    build: .
    image: gamble-btc:latest
    container_name: gamble-btc
    restart: unless-stopped
    env_file: .env
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    group_add:
      - "44"
      - "992"
    ports:
      - "41174:41174"
    mem_limit: 1g
