#!/usr/bin/env python3
"""Generate an interleaved 2-nonce CUDA kernel from the proven single-nonce
round structure (src/cuda/gbtc_mine.cu).

Two adjacent nonces (n0 = base + 2*gid, n1 = n0 + 1) advance in lockstep with
separate state (a..h x2) and separate W schedules (w0..w2 are shared: only
w3 differs at start, the rest diverge). Rounds for A and B are emitted
alternately so the scheduler always has two independent dependency chains.
Output layout and prefilter are unchanged (two compares, one atomic each).
"""
K = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]
ST = "abcdefgh"


def gen():
    L = []
    L.append("// Interleaved 2-nonce variant, GENERATED by scripts/gen-cuda-dual.py.")
    L.append("// Same I/O layout as gbtc_mine; each thread tests base+2*gid and +1.")
    L.append('__device__ __forceinline__ unsigned gpu_ch(unsigned a,unsigned b,unsigned c){unsigned d;asm("lop3.b32 %0, %1, %2, %3, 0xca;":"=r"(d):"r"(a),"r"(b),"r"(c));return d;}')
    L.append('__device__ __forceinline__ unsigned gpu_maj(unsigned a,unsigned b,unsigned c){unsigned d;asm("lop3.b32 %0, %1, %2, %3, 0xe8;":"=r"(d):"r"(a),"r"(b),"r"(c));return d;}')
    L.append("typedef unsigned int uint;")
    L.append("#define ROR(x,n) __funnelshift_r((x),(x),(n))")
    L.append("#define BIGSIG0(x) (ROR(x,2u)^ROR(x,13u)^ROR(x,22u))")
    L.append("#define BIGSIG1(x) (ROR(x,6u)^ROR(x,11u)^ROR(x,25u))")
    L.append("#define SMALLSIG0(x) (ROR(x,7u)^ROR(x,18u)^((x)>>3u))")
    L.append("#define SMALLSIG1(x) (ROR(x,17u)^ROR(x,19u)^((x)>>10u))")
    L.append("#define CH(x,y,z) gpu_ch((x),(y),(z))")
    L.append("#define MAJ(x,y,z) gpu_maj((x),(y),(z))")
    L.append("#define BSWAP32(x) (((x)>>24u)|(((x)>>8u)&0x0000ff00u)|(((x)<<8u)&0x00ff0000u)|((x)<<24u))")
    L.append('extern "C" __global__ void gbtc_mine(const uint *I, uint *O) {')
    L.append("  uint gid = (blockIdx.x * blockDim.x + threadIdx.x);")
    L.append("  uint n0 = I[12] + (gid << 1u), n1 = n0 + 1u;")
    L.append("  uint t1a, t2a, t1b, t2b; (void)t1a; (void)t2a; (void)t1b; (void)t2b;")
    # W: w0..w2 shared; w3..w15 per lane.
    L.append("  uint w0 = I[8], w1 = I[9], w2 = I[10];  // block-1 reads only")
    L.append("  uint w0a = w0, w1a = w1, w2a = w2, w0b = w0, w1b = w1, w2b = w2;")
    L.append("  uint w3a = n0, w3b = n1;")
    L.append("  uint w4a = 0x80000000u, w4b = 0x80000000u;")
    for i in range(5, 15):
        L.append(f"  uint w{i}a = 0u, w{i}b = 0u;")
    L.append("  uint w15a = 640u, w15b = 640u;")
    L.append("  uint aa,ba,ca,da,ea,fa,ga,ha,ab,bb,cb,db,eb,fb,gb,hb;")
    # init state from midstate
    L.append("  aa=I[0]; ba=I[1]; ca=I[2]; da=I[3]; ea=I[4]; fa=I[5]; ga=I[6]; ha=I[7];")
    L.append("  ab=I[0]; bb=I[1]; cb=I[2]; db=I[3]; eb=I[4]; fb=I[5]; gb=I[6]; hb=I[7];")
    # first block, 64 rounds interleaved. W names: lane A uses w{i}a except
    # shared w0..w2; lane B uses w{i}b except shared w0..w2.
    L.append("  // ---- first compression block ----")
    L += interleave_block(0, "a", "b")
    # feed-forward
    for i, c in enumerate(ST):
        L.append(f"  w{i}a = I[{i}] + {c}a; w{i}b = I[{i}] + {c}b;")
    L.append("  w8a = 0x80000000u; w8b = 0x80000000u;")
    for i in list(range(9, 15)):
        L.append(f"  w{i}a = 0u; w{i}b = 0u;")
    L.append("  w15a = 256u; w15b = 256u;")
    L.append("  aa = 0x6a09e667u; ba = 0xbb67ae85u; ca = 0x3c6ef372u; da = 0xa54ff53au;")
    L.append("  ea = 0x510e527fu; fa = 0x9b05688cu; ga = 0x1f83d9abu; ha = 0x5be0cd19u;")
    L.append("  ab = 0x6a09e667u; bb = 0xbb67ae85u; cb = 0x3c6ef372u; db = 0xa54ff53au;")
    L.append("  eb = 0x510e527fu; fb = 0x9b05688cu; gb = 0x1f83d9abu; hb = 0x5be0cd19u;")
    L.append("  // ---- second compression block ----")
    L += interleave_block(1, "a", "b")
    L.append("  if (BSWAP32(0x5be0cd19u + ha) <= I[11]) {")
    L.append("    uint idxa = atomicAdd(O, 1u);")
    L.append("    if (idxa < 15u) O[idxa + 1u] = n0;")
    L.append("  }")
    L.append("  if (BSWAP32(0x5be0cd19u + hb) <= I[11]) {")
    L.append("    uint idxb = atomicAdd(O, 1u);")
    L.append("    if (idxb < 15u) O[idxb + 1u] = n1;")
    L.append("  }")
    L.append("}")
    return "\n".join(L) + "\n"


def interleave_block(second, la, lb):
    """Emit 64 rounds alternating lanes. second=0 uses shared w0..w2 init
    mapping; second=1 uses full per-lane W (w0..w7 from feed-forward)."""
    out = []
    va = [f"{c}a" for c in ST]
    vb = [f"{c}b" for c in ST]

    def wname(lane, i):
        return f"w{i}{lane}"

    for t in range(64):
        # lane A round
        out += round_lines(t, va, la, "t1a", "t2a", wname)
        va = rot(va)
        # lane B round
        out += round_lines(t, vb, lb, "t1b", "t2b", wname)
        vb = rot(vb)
    return out


def rot(v):
    na, ne = v[7], v[3]
    return [na, v[0], v[1], v[2], ne, v[4], v[5], v[6]]


def round_lines(t, v, lane, t1, t2, wname):
    s = t & 15
    lines = []
    if t >= 16:
        s2, s7, s15 = (t - 2) & 15, (t - 7) & 15, (t - 15) & 15
        lines.append(f"  {wname(lane,s)} = {wname(lane,s)} + SMALLSIG0({wname(lane,s15)}) + {wname(lane,s7)} + SMALLSIG1({wname(lane,s2)});")
    wt = wname(lane, s)
    a, b, c, d, e, f, g, h = v
    lines.append(f"  {t1} = {h} + BIGSIG1({e}) + CH({e},{f},{g}) + 0x{K[t]:08x}u + {wt};")
    lines.append(f"  {t2} = BIGSIG0({a}) + MAJ({a},{b},{c});")
    lines.append(f"  {d} = {d} + {t1}; {h} = {t1} + {t2};")
    return lines


if __name__ == "__main__":
    import sys
    sys.stdout.write(gen())
